# Generated by Django 4.1.7 on 2023-05-01 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='carts',
        ),
        migrations.RenameField(
            model_name='cart_item',
            old_name='products',
            new_name='product2',
        ),
    ]
